name: callanother
on: 
  workflow_dispatch:
  pull_request:
  

  #  inputs: 
  #     choose-env: 
  #      description: test
  #      required: true
  #      type: choice
  #      default: dev
  #      options:
  #       - dev
  #       - prod
  #       - uat

permissions:
 id-token: write
 contents: read

jobs: 


 number4:
    uses: ./.github/workflows/mynewtoken.yml
    # with:
    #  choose-env: 'dev'
    secrets: inherit

 initjob:
  uses: ./.github/workflows/init_job.yml
  secrets: inherit