name: myflow-4
on: 
  workflow_dispatch:
   inputs: 
      choose-env: 
       description: test
       required: true
       default: dev
       options:
        - dev
        - prod
        - uat

jobs: 
  myjob: 
   runs-on: ubuntu-latest
   steps:
     - name: my-step
       run: echo "HelloWorld"
  myjob2: 
   runs-on: ubuntu-latest
   steps:
     - name: my-step2
       run: echo "HelloWorld2"