name: myflow-3
on: 
  workflow_call:
    
 
      

jobs: 
  myjob: 
   runs-on: ubuntu-latest
   steps:
     - name: my-step
       run: echo "HelloWorld"
  myjob2: 
   runs-on: ubuntu-latest
   steps:
     - name: my-step2
       run: echo "HelloWorld2"