name: myflow-2
on: push
jobs: 
  myjob: 
   runs-on: ubuntu-latest
   steps:
     - name: my-step
       run: echo "HelloWorld"
  myjob2: 
   runs-on: ubuntu-latest
   steps:
     - name: my-step2
       run: echo "HelloWorld2"