name: tflogin
on: 
  workflow_dispatch:
  workflow_call:
    
   inputs: 
      choose-env: 
       description: test
       required: true
       type: string
       default: dev
       
permissions:
 id-token: write
jobs: 
  devuatb: 
   runs-on: ubuntu-latest
   environment: dev
   steps:
    

     - name: Azure login
       uses: azure/login@v2
       with:
          # client-id: ${{ secrets.client_id_azure}}
          client-id: "3071f7cd-0553-4cd6-8303-d467147aafcc"
          tenant-id: "17a09c66-f406-4897-8b24-51f5313623dc"
          subscription-id: "6e54aa79-9b0b-40ed-ae27-91fdffa0a565"

     - name: get keyvault secret  
       id: access_token_id

       
       run: |
        # value1=$(az keyvault secret show --name test --vault-name ibo-rg-kv1 --query value -o tsv)
        echo "value1=$(az keyvault secret show --name test --vault-name ibo-rg-kv1 --query value -o tsv)"
        # echo "Secret Value: $value1"
        # echo "KVSECRET_VALUE=$value1" >> $GITHUB_ENV
        # echo "$value1" >> $GITHUB_ENV
        echo "mytoken = $value1" >> $GITHUB_ENV
        # echo "mytoken = $value1" >> $GITHUB_OUTPUT

     - name: show secret
     
       
       run: |
       
        echo "$mytoken"

    #  - name: set terraform token
    #    run: |
    #       mkdir ${HOME}/.terraform.d
    #       cat > ${HOME}/.terraform.d/credentials.tfrc.json << EOF
    #       {
    #         "credentials": {
    #           "app.terraform.io": {
    #             "token": ${{steps.access_token_id.outputs.value2}}
    #           }
    #         }
    #       }
    #       EOF

 